MESSAGE(NEW_GAME_EASY,
	"New game (Easy)",
	"Новая игра (Лёгкая)")

MESSAGE(NEW_GAME_DIFFICULT,
	"New game (Difficult)",
	"Новая игра (Тяжёлая)")

MESSAGE(NEW_GAME_FOUR_BRIDGES,
	"New game (Four Bridges)",
	"Новая игра (Четыре моста)")

MESSAGE(EXIT,
	"Exit",
	"Выход")

MESSAGE(CHANGE_ORIENTATION,
	"Change screen orientation",
	"Сменить ориентацию экрана")

MESSAGE(CONTINUE,
	"Continue",
	"Продолжить")

MESSAGE(HINT,
	"Hint",
	"Подсказать")

MESSAGE(UNDO,
	"Undo",
	"Отменить ход")

MESSAGE(TOGGLE_LANGUAGE,
	"Русский",
	"English")

MESSAGE(WIN,
	"Solitaire is solved. Congratulations!",
	"Пасьянс решён. Поздравляем!")

MESSAGE(LOSE,
	"There is no more free pair. You lose",
	"Свободных пар больше нет. Вы проиграли.")

MESSAGE(MOVES_LEFT,
	"Available pairs: %d",
	"Доступно пар: %d")

MESSAGE(HELP,
	"←, ↑, →, ↓ - cursor movement, OK - select chip, Menu - game menu",
	"←, ↑, →, ↓ - перемещение курсора, OK - выбор камня, Menu - меню игры")

